name: circle_cue
description: A very basic Flutter Android application.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  drift: ^2.14.1
  sqlite3: ^2.4.0
  sqlite3_flutter_libs: ^0.5.0
  path: ^1.8.0
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  drift_dev: ^2.14.1
  build_runner: ^2.4.0

flutter:
  uses-material-design: true 